application: hack-your-education
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /sources
  static_dir: sources

- url: /.*
  script: hack-your-education.application

libraries:
- name: jinja2
  version: latest

